version: "3.7"
services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
      - "./app:/app"
    ports:
      - 3000:3000
    restart: "always"
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - react
